import {mobileCheck} from "../utils/helpers";

const isMobile = mobileCheck();
const THREAD_HISTORY_LIMIT_PER_REQUEST = 20;
const THREAD_HISTORY_MAX_RENDERED = THREAD_HISTORY_LIMIT_PER_REQUEST * (isMobile ? 3 : 3);
const THREAD_HISTORY_UNSEEN_MENTIONED = 100;

export {THREAD_HISTORY_LIMIT_PER_REQUEST, THREAD_HISTORY_MAX_RENDERED, THREAD_HISTORY_UNSEEN_MENTIONED}
