const THREAD_HISTORY_LIMIT_PER_REQUEST = 20;
const THREAD_HISTORY_RENDERED = THREAD_HISTORY_LIMIT_PER_REQUEST * 5;
const THREAD_HISTORY_UNSEEN_MENTIONED = 100;

export {THREAD_HISTORY_LIMIT_PER_REQUEST, THREAD_HISTORY_RENDERED, THREAD_HISTORY_UNSEEN_MENTIONED}
