export const THREAD_REMOVE_MESSAGE = "THREAD_REMOVE_MESSAGE";
export const THREAD_INFO_UPDATE = "THREAD_INFO_UPDATE";
export const THREAD_ADD_MEMBER = "THREAD_ADD_MEMBER";
export const THREAD_REMOVE_MEMBER = "THREAD_REMOVE_MEMBER";
export const THREAD_PIN_MESSAGE = "THREAD_PIN_MESSAGE";
export const THREAD_ADMIN = "THREAD_ADMIN";

